version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/app
      - ./test/models:/models/
      - ./test/samples:/samples/
    ports:
      - "8095:8095"
    environment:
      - FILE_PERMISSIONS_GID=1000
      - FILE_PERMISSIONS_UID=1000
      - LOG_LEVEL=TRACE
      - MODEL_TYPE=medium
      - VERIFY_MODEL_HASH=false